// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2, arg3) {
  return window['go']['backend']['App']['Add'](arg1, arg2, arg3);
}

export function AllData() {
  return window['go']['backend']['App']['AllData']();
}

export function Delete(arg1) {
  return window['go']['backend']['App']['Delete'](arg1);
}

export function Generate(arg1) {
  return window['go']['backend']['App']['Generate'](arg1);
}

export function Search(arg1) {
  return window['go']['backend']['App']['Search'](arg1);
}
