// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function Palindrome(arg1) {
  return window['go']['main']['App']['Palindrome'](arg1);
}
