// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Add'](arg1, arg2, arg3, arg4);
}

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}
