// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Check(arg1:string):Promise<string>;

export function Delete(arg1:string):Promise<string>;

export function Generate(arg1:number):Promise<string>;
